[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
metaloot_registry_program = "v3MbKaZSQJrwZWUz81cQ3kc8XvMsiNNxZjM3vN5BB32"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/metaloot-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
